version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 88:80
      - 443:443
    volumes:
      # - /home/dimka/Documents/Projects/nextcloud-with-apps/nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

  elasticsearch:
    # DOCKER_TAG will be provided by the .env-file
    image: r0wi/elasticsearch-nextcloud-docker:7.6.1
    container_name: elasticsearch_nc
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # Use named volume because of permission problems
      - elasticsearch_data:/usr/share/elasticsearch/data 
    ports:
      - 127.0.0.1:9200:9200
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /docker/nextcloud/redis:/data
    restart: unless-stopped
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
  elasticsearch_data:
  db:

